// Shared portfolio data — single source of truth for all 3 variations
window.PORTFOLIO_DATA = {
  name: "Bakytbek Tatibekov",
  shortName: "Bakytbek",
  initials: "BT",
  role: "Sr. Software Engineer",
  location: "Available remote · Open to roles",
  email: "hello@example.com", // placeholder
  resumeUrl: "resume.pdf",
  socials: [
    { label: "GitHub", handle: "@beckinfonet", url: "https://github.com/beckinfonet" },
    { label: "LinkedIn", handle: "in/beckinfonet", url: "#" },
    { label: "Email", handle: "hello@example.com", url: "mailto:hello@example.com" },
  ],
  bio: {
    short: "Full-stack engineer with ~7 years building scalable web apps in JS, React and AWS. Currently shipping AI-native products at the intersection of logistics, identity, and agentic workflows.",
    long: [
      "Software engineer with ~7 years of experience building scalable web applications, specializing in JavaScript, React, and cloud-native architectures on AWS. Recently focused on generative AI and agentic systems, with hands-on work using LangChain and MCP-style integrations to turn conversational workflows into real-world automation.",
      "Currently building products at the intersection of AI and logistics — identity verification and fraud prevention platforms, plus AI-driven booking systems. Strong interest in MLOps, data workflows, and designing systems that bridge practical business problems with modern AI capabilities.",
    ],
  },
  highlights: [
    { value: "7+", label: "Years shipping" },
    { value: "AWS", label: "Cloud-native" },
    { value: "AI", label: "Agentic systems" },
  ],
  projects: [
    {
      name: "Agentic Booking Platform",
      year: "2025",
      status: "In production",
      summary: "AI-driven booking system that turns conversational intent into multi-step logistics workflows. LangChain agents orchestrate carrier APIs, pricing, and human-in-the-loop approvals.",
      tech: ["React", "Node.js", "LangChain", "AWS Lambda", "Postgres"],
      role: "Tech lead",
      link: "#",
    },
    {
      name: "Identity & Fraud Prevention",
      year: "2024",
      status: "Live",
      summary: "Document verification + behavioral signal pipeline for logistics carriers. Reduced onboarding fraud by combining OCR, vector similarity, and rule-based scoring.",
      tech: ["TypeScript", "Python", "Pinecone", "AWS", "OpenCV"],
      role: "Senior engineer",
      link: "#",
    },
    {
      name: "MCP Integration Layer",
      year: "2025",
      status: "Internal",
      summary: "Model-Context-Protocol style integration layer that exposes internal tools to LLM agents. Standardized 12+ business systems behind a single conversational interface.",
      tech: ["TypeScript", "MCP", "OpenAI", "Anthropic", "Redis"],
      role: "Architect",
      link: "#",
    },
    {
      name: "MLOps Data Workflows",
      year: "2024",
      status: "Shipped",
      summary: "Feature store + evaluation pipeline for production AI features. Enabled rapid iteration on prompts and models without breaking downstream consumers.",
      tech: ["Python", "Airflow", "DBT", "Snowflake", "MLflow"],
      role: "Senior engineer",
      link: "#",
    },
    {
      name: "React Component Library",
      year: "2023",
      status: "Open source",
      summary: "Internal design system used across 4 product teams. Headless, themeable components built on Radix primitives with strict accessibility standards.",
      tech: ["React", "TypeScript", "Radix", "CSS-in-JS", "Storybook"],
      role: "Maintainer",
      link: "#",
    },
    {
      name: "Edge Caching Service",
      year: "2022",
      status: "Shipped",
      summary: "CloudFront-fronted edge cache for high-traffic carrier API. Reduced p99 latency from 800ms to 90ms and cut origin egress 70%.",
      tech: ["Node.js", "AWS CloudFront", "Lambda@Edge", "DynamoDB"],
      role: "Senior engineer",
      link: "#",
    },
  ],
  stack: {
    Languages: ["JavaScript", "TypeScript", "Python", "Go", "SQL"],
    Frontend: ["React", "Next.js", "Remix", "TailwindCSS", "Radix"],
    Backend: ["Node.js", "Express", "FastAPI", "GraphQL", "REST"],
    "AI / ML": ["LangChain", "MCP", "OpenAI", "Anthropic", "Pinecone", "MLflow"],
    Cloud: ["AWS", "Lambda", "ECS", "CloudFront", "S3", "Terraform"],
    Data: ["Postgres", "DynamoDB", "Redis", "Snowflake", "Airflow", "DBT"],
  },
  experience: [
    {
      company: "Logistics & AI Co.",
      role: "Sr. Software Engineer",
      period: "2023 — Present",
      summary: "Leading AI-native product work — agentic booking, identity verification, and the MCP integration layer powering internal automation.",
    },
    {
      company: "Previous Tech Co.",
      role: "Software Engineer → Senior",
      period: "2020 — 2023",
      summary: "Built and scaled customer-facing React apps and Node.js services on AWS. Owned the design system and edge caching infrastructure.",
    },
    {
      company: "Earlier Startup",
      role: "Software Engineer",
      period: "2018 — 2020",
      summary: "Full-stack work across web, mobile, and data pipelines. Shipped the company's first production ML feature.",
    },
  ],
  writing: [
    {
      title: "Designing MCP servers for real workflows",
      date: "Mar 2025",
      readTime: "8 min",
      excerpt: "What I learned wiring 12+ business systems behind an LLM-facing protocol — and where the abstraction breaks down.",
    },
    {
      title: "From chatbot to agent: the cost of statefulness",
      date: "Nov 2024",
      readTime: "6 min",
      excerpt: "Notes on moving a customer-support chatbot to a multi-step agent. Latency, cost, and the awkward middle ground.",
    },
    {
      title: "Edge caching a chatty API",
      date: "Aug 2024",
      readTime: "5 min",
      excerpt: "How we cut p99 latency 9x by moving auth and rate limiting to Lambda@Edge — and what it cost us in debugging tools.",
    },
  ],
};
